goalapp_sol/solution/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:index, :show, :new, :create]
  resources :goals do
    resources :cheers, only: [:create]
  end
  resources :cheers, only: [:index]
  resources :comments, only: [:create]
end

goalapp_sol/solution/app/views/shared/_cheer_button.html.erb
<form action="<%= goal_cheers_url(goal) %>" method="POST">
  <input type="hidden" name="authenticity_token" 
    value="<%= form_authenticity_token %>">
  <input type="submit" value="Cheer!">
</form>

goalapp_sol/solution/app/views/shared/_comments_form.html.erb
<h3>New Comment</h3>

<%= render 'shared/errors' %>

<form action="<%= comments_url %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="comment[commentable_id]" value="<%= commentable_id %>">
  <input type="hidden" name="comment[commentable_type]" value="<%= commentable_type %>">
  <label>Comment
    <textarea name="comment[body]"></textarea>
  </label>
  <input type="submit" value="Save Comment">
</form>

goalapp_sol/solution/app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <div class="errors">
    <% flash[:errors].each do |msg| %>
      <p><b><%= msg %></b></p>
    <% end %>
  </div>
<% end %>

goalapp_sol/solution/app/views/shared/_goal_complete_button.html.erb
<form action="<%= goal_url(goal) %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PUT">
  <input type="hidden" name="goal[completed]" value="<%= !goal.completed %>">
  <input type="submit"
  <% if goal.completed %>
  value="Oops!  Did not complete."
  <% else %>
  value="Complete"
  <% end %>
  id="goal_<%= goal.id %>_completed">
</form>

goalapp_sol/solution/app/views/shared/_show_goal_basics.html.erb
<% privacy = (goal.private) ? "private" : "public" %>
<% completedness = (goal.completed) ? "Complete" : "Ongoing"%>

<li>
  <a href="<%= goal_url(goal) %>"><%= goal.title %></a>
  <p><i><%= privacy %></i></p>
  <p><i><%= completedness %></i></p>
  <br>

  <% if current_user && current_user.id == goal.user_id %>
    <%= render "shared/goal_complete_button", goal: goal %>
    <br>
    <form action="<%= goal_url(goal) %>" method="post">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="<%= "delete '#{goal.title}' goal" %>">
      </form>
  <% elsif current_user && !(goal.cheered_by?(current_user)) && current_user.cheer_count > 0 %>
    <%= render "shared/cheer_button", goal: goal %>
  <% end %>
</li>

goalapp_sol/solution/app/views/shared/_user_form.html.erb
<% action = (type == :newuser) ? users_url : session_url %>
<% button_text = (type == :newuser) ? "Sign Up" : "Log In" %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label>Username:
    <input type="text" value="<%= @user.username %>" name="user[username]">
  </label>
  <br>

  <label>Password:
    <input type="password" value="<%= @user.password %>" name="user[password]">
  </label>
  <br>

  <input type="submit" value="<%= button_text %>">
</form>