goalapp_sol/solution/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:index, :show, :new, :create]
  resources :goals do
    resources :cheers, only: [:create]
  end
  resources :cheers, only: [:index]
  resources :comments, only: [:create]
end

goalapp_sol/solution/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goal App</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <h1>GOALING APP</h1>
  <% if flash[:notices] %>
    <div class="notices">
      <% flash[:notices].each do |msg| %>
        <p><b><%= msg %></b></p>
      <% end %>
    </div>
  <% end %>

  <div class="pull-right">
    <% if current_user %>
      <p>Welcome <%= current_user_name %></p>
      <form action="<%= session_url %>" method="post">
        <input
          type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Log Out">
      </form>

      <p>Cheers Remaining:
        <span id="cheer-limit"><%= current_user.cheer_count %></span>
      </p>
    <% else %>
      <p><a href="<%= new_user_url %>">Sign Up</a></p>
      <p>or</p>
      <p><a href="<%= new_session_url %>">Log In</a></p>
    <% end %>
  </div>
</header>

<%= yield %>

</body>
</html>